#[global.databases]
#sql_log = { url = "./log_database.sqlite3" }

[development]
address = "localhost"
databases = {sql_log = { url = "./log_database_test.sqlite3" }}

[production]
address = "0.0.0.0"
databases = {sql_log = { url = "./log_database.sqlite3" }}
